import { InvoiceData } from "@/lib/schema";
import { getTemplateUtils } from "../lib/template-utils";
import { SignatureBlock } from "./SignatureBlock";

interface TemplateProps {
  data: InvoiceData;
}

export function SalariesTemplate({ data }: TemplateProps) {
  const { formatCurrency, subtotal, tax, discountAmount, total } = getTemplateUtils(data);

  return (
    <div className="w-full h-full min-h-full bg-white p-10 flex flex-col font-sans text-slate-800 box-border">
      <div className="border-b-4 border-slate-800 pb-5 mb-8 flex justify-between items-end">
        <div>
          {data.logoUrl && (
            <img src={data.logoUrl} alt="Logo" className="max-h-12 max-w-[160px] object-contain mb-3" />
          )}
          <div className="text-3xl font-black tracking-tighter mb-1 select-none">PAYSLIP</div>
          <div className="text-xs font-bold text-slate-500">{data.invoiceNumber || "PY-001"}</div>
        </div>
        <div className="text-right">
          <div className="font-bold text-base">{data.businessName || "Employer Name"}</div>
          <div className="text-slate-500 text-xs">{data.businessEmail}</div>
          {data.phone && <div className="text-slate-500 text-[10px]">{data.phone}</div>}
          {data.website && <div className="text-slate-500 text-[10px]">{data.website}</div>}
          {data.taxId && <div className="text-slate-500 text-[10px] mt-0.5">Tax ID: {data.taxId}</div>}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8 bg-slate-50 p-5 rounded-lg border border-slate-200">
        <div className="space-y-1">
          <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Employee Information</div>
          <div className="font-bold text-sm text-slate-900">{data.clientName || "Employee Name"}</div>
          {data.clientEmail && <div className="text-xs text-slate-600 truncate">{data.clientEmail}</div>}
          <div className="text-xs text-slate-600 whitespace-pre-wrap">{data.clientAddress}</div>
        </div>
        <div className="space-y-1.5 text-xs text-right">
          <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Payment Details</div>
          <div className="flex justify-between gap-4"><span className="text-slate-500">Pay Date:</span> <span className="font-bold">{data.issueDate || "-"}</span></div>
          <div className="flex justify-between gap-4"><span className="text-slate-500">Pay Period:</span> <span className="font-bold">{data.issueDate || "-"} — {data.dueDate || "-"}</span></div>
        </div>
      </div>

      <div className="flex-1">
        <table className="w-full border-collapse">
          <thead>
            <tr className="border-b-2 border-slate-800">
              <th className="py-2.5 text-left text-xs font-black uppercase tracking-widest text-slate-500">Earnings Description</th>
              <th className="py-2.5 text-right text-xs font-black uppercase tracking-widest text-slate-500 w-24">Qty/Hrs</th>
              <th className="py-2.5 text-right text-xs font-black uppercase tracking-widest text-slate-500 w-28">Rate / Salary</th>
              <th className="py-2.5 text-right text-xs font-black uppercase tracking-widest text-slate-500 w-28">Total</th>
            </tr>
          </thead>
          <tbody>
            {data.lineItems && data.lineItems.length > 0 ? (
              data.lineItems.map((item, i) => (
                <tr key={item.id || i} className="border-b border-slate-100">
                  <td className="py-3 font-bold text-sm text-slate-800 break-words whitespace-pre-wrap pr-2">{item.description || "—"}</td>
                  <td className="py-3 text-right text-sm text-slate-500">{item.quantity ?? 0}</td>
                  <td className="py-3 text-right text-sm text-slate-500">{formatCurrency(item.unitPrice || 0)}</td>
                  <td className="py-3 text-right font-bold text-sm text-slate-900">{formatCurrency((Number(item.quantity) || 0) * (Number(item.unitPrice) || 0))}</td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={4} className="py-8 text-center text-slate-400 text-sm italic">No earnings records added yet</td>
              </tr>
            )}
          </tbody>
        </table>

        <div className="mt-8 flex justify-between items-end gap-6">
          <div className="flex-1 max-w-sm">
            {data.notes ? (
              <div className="mb-4">
                <div className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-1">Notes / Terms</div>
                <p className="text-xs text-slate-600 whitespace-pre-wrap leading-relaxed">{data.notes}</p>
              </div>
            ) : null}
            <div className="text-[10px] text-slate-400 uppercase tracking-[0.2em] mb-4">
              Electronic records &middot; generated by {data.businessName || "InvoiceKit"}
            </div>
            <SignatureBlock signature={data.signature} />
          </div>
          <div className="w-72 bg-slate-900 text-white p-5 rounded-xl shadow-lg shrink-0">
            <div className="space-y-2 text-sm mb-3">
              <div className="flex justify-between text-slate-400">
                <span>Gross Pay</span>
                <span className="font-semibold text-white">{formatCurrency(subtotal)}</span>
              </div>
              {Number(data.taxRate) > 0 && (
                <div className="flex justify-between text-rose-400">
                  <span>Tax Withheld ({data.taxRate}%)</span>
                  <span>-{formatCurrency(tax)}</span>
                </div>
              )}
              {Number(data.discount) > 0 && (
                <div className="flex justify-between text-emerald-400">
                  <span>Bonus/Other ({data.discount}%)</span>
                  <span>+{formatCurrency(discountAmount)}</span>
                </div>
              )}
            </div>
            <div className="border-t border-slate-700 pt-3 flex justify-between items-end">
              <div className="text-xs font-black uppercase tracking-widest text-slate-400">Net Take Home</div>
              <div className="text-xl font-black text-white">{formatCurrency(total)}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
